[tool.poetry]
name = "twitter-scraper-safeyelli"
version = "0.1.0"
description = "For "
authors = ["Adhavan"]

[tool.poetry.dependencies]
python = "^3.8"
snscrape = "^0.5.0.20230113"
replit = "^3.0.0"